#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
Generate C tables for the EtherCAT slave: identity registers + Object Dictionary.

Emits generated/ul_ecat_slave_tables.{c,h} containing:
  - ul_ecat_generated_slave_identity (vendor/product/revision/serial)
  - ul_ecat_generated_od_table (CoE Object Dictionary entries)
  - ul_ecat_generated_od_count

The OD currently includes the CiA 301 mandatory objects:
  0x1000 Device Type, 0x1008 Device Name, 0x1009 HW Version, 0x100A SW Version,
  0x1018 Identity (5 subindexes: count + vendor/product/revision/serial).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _str_pad(s: str, n: int) -> bytes:
    b = s.encode("utf-8")[:n]
    return b + b"\0" * (n - len(b))


def _c_array_bytes(b: bytes) -> str:
    return ", ".join(f"0x{x:02X}" for x in b)


def emit_header(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """/* Generated by scripts/gen_slave_data.py - do not edit by hand. */

#ifndef UL_ECAT_SLAVE_TABLES_H
#define UL_ECAT_SLAVE_TABLES_H

#include <stddef.h>
#include "ul_ecat_slave.h"
#include "ul_ecat_slave_od.h"

extern const ul_ecat_slave_identity_t ul_ecat_generated_slave_identity;

extern const ul_ecat_od_table_t ul_ecat_generated_od_table;

#endif
""",
        encoding="utf-8",
    )


def emit_source(
    path: Path,
    vendor: int,
    product: int,
    revision: int,
    serial: int,
    device_type: int,
    device_name: str,
    hw_version: str,
    sw_version: str,
    str_len: int,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    name_bytes = _str_pad(device_name, str_len)
    hw_bytes = _str_pad(hw_version, str_len)
    sw_bytes = _str_pad(sw_version, str_len)

    src = f"""/* Generated by scripts/gen_slave_data.py - do not edit by hand. */

#include "ul_ecat_slave_tables.h"

const ul_ecat_slave_identity_t ul_ecat_generated_slave_identity = {{
    .vendor_id = 0x{vendor:08X}u,
    .product_code = 0x{product:08X}u,
    .revision = 0x{revision:08X}u,
    .serial = 0x{serial:08X}u,
}};

/* CoE Object Dictionary backing storage. Mutable so the slave can serve writes
 * (entries marked RO are still rejected at runtime by the OD lookup flags). */

static uint32_t od_device_type = 0x{device_type:08X}u;
static uint8_t  od_device_name[{str_len}] = {{ {_c_array_bytes(name_bytes)} }};
static uint8_t  od_hw_version[{str_len}]  = {{ {_c_array_bytes(hw_bytes)} }};
static uint8_t  od_sw_version[{str_len}]  = {{ {_c_array_bytes(sw_bytes)} }};

static uint8_t  od_identity_count    = 4u;
static uint32_t od_identity_vendor   = 0x{vendor:08X}u;
static uint32_t od_identity_product  = 0x{product:08X}u;
static uint32_t od_identity_revision = 0x{revision:08X}u;
static uint32_t od_identity_serial   = 0x{serial:08X}u;

static const ul_ecat_od_entry_t ul_ecat_generated_od_entries[] = {{
    {{0x1000, 0x00, UL_ECAT_OD_TYPE_U32,    UL_ECAT_OD_FLAG_R, 4,            &od_device_type}},
    {{0x1008, 0x00, UL_ECAT_OD_TYPE_STRING, UL_ECAT_OD_FLAG_R, {str_len}u, od_device_name}},
    {{0x1009, 0x00, UL_ECAT_OD_TYPE_STRING, UL_ECAT_OD_FLAG_R, {str_len}u, od_hw_version}},
    {{0x100A, 0x00, UL_ECAT_OD_TYPE_STRING, UL_ECAT_OD_FLAG_R, {str_len}u, od_sw_version}},
    {{0x1018, 0x00, UL_ECAT_OD_TYPE_U8,     UL_ECAT_OD_FLAG_R, 1,            &od_identity_count}},
    {{0x1018, 0x01, UL_ECAT_OD_TYPE_U32,    UL_ECAT_OD_FLAG_R, 4,            &od_identity_vendor}},
    {{0x1018, 0x02, UL_ECAT_OD_TYPE_U32,    UL_ECAT_OD_FLAG_R, 4,            &od_identity_product}},
    {{0x1018, 0x03, UL_ECAT_OD_TYPE_U32,    UL_ECAT_OD_FLAG_R, 4,            &od_identity_revision}},
    {{0x1018, 0x04, UL_ECAT_OD_TYPE_U32,    UL_ECAT_OD_FLAG_R, 4,            &od_identity_serial}},
}};

const ul_ecat_od_table_t ul_ecat_generated_od_table = {{
    ul_ecat_generated_od_entries,
    sizeof(ul_ecat_generated_od_entries) / sizeof(ul_ecat_generated_od_entries[0]),
}};
"""
    path.write_text(src, encoding="utf-8")


def print_table(vendor: int, product: int, revision: int, serial: int,
                device_type: int, device_name: str, hw_version: str, sw_version: str) -> None:
    rows_id = [
        ("vendor_id", f"0x{vendor:08X}", "0x0012", "4"),
        ("product_code", f"0x{product:08X}", "0x0016", "4"),
        ("revision", f"0x{revision:08X}", "0x001A", "4"),
        ("serial", f"0x{serial:08X}", "0x001E", "4"),
    ]
    w = max(len(r[0]) for r in rows_id) + 2
    print("ul_ecat slave identity (ESC register map, LE)")
    print(f"{'field':<{w}}{'value':<14}{'ADO':<10}{'len'}")
    print("-" * (w + 14 + 10 + 6))
    for name, val, ado, ln in rows_id:
        print(f"{name:<{w}}{val:<14}{ado:<10}{ln}")

    print("\nCoE Object Dictionary entries (generated)")
    od_rows = [
        ("0x1000:00", f"0x{device_type:08X}", "U32",    "Device Type"),
        ("0x1008:00", repr(device_name),       "STRING", "Device Name"),
        ("0x1009:00", repr(hw_version),        "STRING", "HW Version"),
        ("0x100A:00", repr(sw_version),        "STRING", "SW Version"),
        ("0x1018:00", "4",                     "U8",     "Identity count"),
        ("0x1018:01", f"0x{vendor:08X}",       "U32",    "Vendor"),
        ("0x1018:02", f"0x{product:08X}",      "U32",    "Product"),
        ("0x1018:03", f"0x{revision:08X}",     "U32",    "Revision"),
        ("0x1018:04", f"0x{serial:08X}",       "U32",    "Serial"),
    ]
    print(f"{'index:sub':<12}{'value':<22}{'type':<8}{'name'}")
    print("-" * 60)
    for idx, val, ty, nm in od_rows:
        print(f"{idx:<12}{val:<22}{ty:<8}{nm}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--vendor", type=lambda x: int(x, 0), default=0x00000002)
    p.add_argument("--product", type=lambda x: int(x, 0), default=0x1C213052)
    p.add_argument("--revision", type=lambda x: int(x, 0), default=0x00000001)
    p.add_argument("--serial", type=lambda x: int(x, 0), default=0x00000001)
    p.add_argument("--device-type", type=lambda x: int(x, 0), default=0x00000000)
    p.add_argument("--device-name", default="ul_ecat slave")
    p.add_argument("--hw-version", default="rev1")
    p.add_argument("--sw-version", default="0.1")
    p.add_argument("--str-len", type=int, default=32, help="Fixed length for OD strings (NUL-padded)")
    p.add_argument("--out-dir", type=Path, default=None, help="Output dir (default: repo generated/)")
    p.add_argument("--stdout-only", action="store_true")
    args = p.parse_args()

    print_table(
        args.vendor, args.product, args.revision, args.serial,
        args.device_type, args.device_name, args.hw_version, args.sw_version,
    )
    if args.stdout_only:
        return 0

    repo = Path(__file__).resolve().parent.parent
    out_dir = args.out_dir or (repo / "generated")
    emit_header(out_dir / "ul_ecat_slave_tables.h")
    emit_source(
        out_dir / "ul_ecat_slave_tables.c",
        args.vendor, args.product, args.revision, args.serial,
        args.device_type, args.device_name, args.hw_version, args.sw_version,
        args.str_len,
    )
    print(f"Wrote {out_dir}/ul_ecat_slave_tables.{{c,h}}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
