#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
Generate C tables for default EtherCAT slave identity registers (little-endian DWORDs).

Prints an ASCII table to stdout and writes generated/ul_ecat_slave_tables.c and .h unless --stdout-only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def emit_c_source(path: Path, vendor: int, product: int, revision: int, serial: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""/* Generated by scripts/gen_slave_data.py — do not edit by hand. */

#include "ul_ecat_slave_tables.h"

const ul_ecat_slave_identity_t ul_ecat_generated_slave_identity = {{
    .vendor_id = 0x{vendor:08X}u,
    .product_code = 0x{product:08X}u,
    .revision = 0x{revision:08X}u,
    .serial = 0x{serial:08X}u,
}};
""",
        encoding="utf-8",
    )


def print_table(vendor: int, product: int, revision: int, serial: int) -> None:
    rows = [
        ("vendor_id", f"0x{vendor:08X}", "0x0012", "4"),
        ("product_code", f"0x{product:08X}", "0x0016", "4"),
        ("revision", f"0x{revision:08X}", "0x001A", "4"),
        ("serial", f"0x{serial:08X}", "0x001E", "4"),
    ]
    w = max(len(r[0]) for r in rows) + 2
    print("ul_ecat slave identity (ESC register map, LE)")
    print(f"{'field':<{w}}{'value':<14}{'ADO':<10}{'len'}")
    print("-" * (w + 14 + 10 + 6))
    for name, val, ado, ln in rows:
        print(f"{name:<{w}}{val:<14}{ado:<10}{ln}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--vendor", type=lambda x: int(x, 0), default=0x00000002)
    p.add_argument("--product", type=lambda x: int(x, 0), default=0x1C213052)
    p.add_argument("--revision", type=lambda x: int(x, 0), default=0x00000001)
    p.add_argument("--serial", type=lambda x: int(x, 0), default=0x00000001)
    p.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory for .c/.h (default: repo generated/)",
    )
    p.add_argument("--stdout-only", action="store_true", help="Print table only, do not write files")
    args = p.parse_args()

    print_table(args.vendor, args.product, args.revision, args.serial)

    if args.stdout_only:
        return 0

    repo = Path(__file__).resolve().parent.parent
    out_dir = args.out_dir or (repo / "generated")
    h_path = out_dir / "ul_ecat_slave_tables.h"
    c_path = out_dir / "ul_ecat_slave_tables.c"
    h_path.write_text(
        """/* Generated by scripts/gen_slave_data.py — do not edit by hand. */

#ifndef UL_ECAT_SLAVE_TABLES_H
#define UL_ECAT_SLAVE_TABLES_H

#include "ul_ecat_slave.h"

extern const ul_ecat_slave_identity_t ul_ecat_generated_slave_identity;

#endif
""",
        encoding="utf-8",
    )
    emit_c_source(c_path, args.vendor, args.product, args.revision, args.serial)
    print(f"Wrote {c_path} and {h_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
