/**
 * @file ul_ecat_slave_od.h
 * @brief CANopen Object Dictionary (OD) framework for the EtherCAT slave (CoE).
 *
 * Each OD entry is identified by (index, subindex). Entries point to a backing
 * storage area (typically a const or extern variable) and carry a type and
 * access flags (RO/WO/RW). The table itself is supplied by the application;
 * generated by scripts/gen_slave_data.py for the default identity objects.
 */

#ifndef UL_ECAT_SLAVE_OD_H
#define UL_ECAT_SLAVE_OD_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Object Dictionary value types (CiA 301 subset). */
typedef enum ul_ecat_od_type {
    UL_ECAT_OD_TYPE_BOOL = 0x01,
    UL_ECAT_OD_TYPE_I8   = 0x02,
    UL_ECAT_OD_TYPE_I16  = 0x03,
    UL_ECAT_OD_TYPE_I32  = 0x04,
    UL_ECAT_OD_TYPE_U8   = 0x05,
    UL_ECAT_OD_TYPE_U16  = 0x06,
    UL_ECAT_OD_TYPE_U32  = 0x07,
    UL_ECAT_OD_TYPE_REAL32 = 0x08,
    UL_ECAT_OD_TYPE_STRING = 0x09,
    UL_ECAT_OD_TYPE_OCTET_STRING = 0x0A,
} ul_ecat_od_type_t;

/** Access flags. */
#define UL_ECAT_OD_FLAG_R   0x01u  /* readable */
#define UL_ECAT_OD_FLAG_W   0x02u  /* writable */
#define UL_ECAT_OD_FLAG_RW  (UL_ECAT_OD_FLAG_R | UL_ECAT_OD_FLAG_W)

typedef struct ul_ecat_od_entry {
    uint16_t index;
    uint8_t  subindex;
    uint8_t  type;     /* ul_ecat_od_type_t */
    uint8_t  flags;    /* UL_ECAT_OD_FLAG_* */
    uint16_t length;   /* storage capacity in bytes */
    void    *storage;  /* pointer to backing data (LE for numerics) */
} ul_ecat_od_entry_t;

/** OD table the slave consults; the application sets it once via @ref ul_ecat_od_set_table. */
typedef struct ul_ecat_od_table {
    const ul_ecat_od_entry_t *entries;
    size_t count;
} ul_ecat_od_table_t;

/** Result codes for OD operations. */
#define UL_ECAT_OD_OK                 0
#define UL_ECAT_OD_ERR_NOT_FOUND      (-1)  /* index missing */
#define UL_ECAT_OD_ERR_BAD_SUBINDEX   (-2)  /* index found, subindex missing */
#define UL_ECAT_OD_ERR_NOT_READABLE   (-3)
#define UL_ECAT_OD_ERR_NOT_WRITABLE   (-4)
#define UL_ECAT_OD_ERR_LENGTH         (-5)  /* dst buffer too small / src too big */

/**
 * Install the OD table (typically from generated/ul_ecat_slave_tables.c).
 * Pass @c NULL to clear (lookups will return ERR_NOT_FOUND).
 */
void ul_ecat_od_set_table(const ul_ecat_od_table_t *table);

/**
 * Find an entry by (index, subindex).
 * @return entry pointer (within installed table) or NULL if not found.
 */
const ul_ecat_od_entry_t *ul_ecat_od_lookup(uint16_t index, uint8_t subindex);

/**
 * Find any subindex for an index (used for index-existence checks and "subindex 0" handling).
 * @return non-zero if at least one entry with @p index exists.
 */
int ul_ecat_od_index_exists(uint16_t index);

/** Pointer to the first entry of the installed table (NULL if none). */
const ul_ecat_od_entry_t *ul_ecat_od_first(void);

/** Number of entries in the installed table. */
size_t ul_ecat_od_entries_count(void);

/**
 * Read up to @p cap bytes from the entry's storage into @p dst.
 * For string types reads up to @c entry->length bytes (caller may trim trailing NUL externally).
 * @return number of bytes copied (>=0) or negative UL_ECAT_OD_ERR_*.
 */
int ul_ecat_od_read(const ul_ecat_od_entry_t *entry, void *dst, size_t cap);

/**
 * Write @p len bytes from @p src into the entry's storage.
 * @return UL_ECAT_OD_OK or negative error.
 */
int ul_ecat_od_write(const ul_ecat_od_entry_t *entry, const void *src, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* UL_ECAT_SLAVE_OD_H */
